#include "bridge.hpp"

#undef __BRIDGE_HPP__
#undef BOOST_HAS_INT128
#undef BRIDGE_CPP_VERSION
#undef BRIDGE_VERSION
#undef $aelse
#undef $apple
#undef $bits32
#undef $bits64
#undef $celse
#undef $clang
#undef $comment
#undef $cpp03
#undef $cpp11
#undef $debug
#undef $devel
#undef $gelse
#undef $gnuc
#undef $has
#undef $ielse
#undef $ios
#undef $is
#undef $lelse
#undef $likely
#undef $linux
#undef $melse
#undef $msvc
#undef $no
#undef $oelse
#undef $on
#undef $osx
#undef $public
#undef $quote
#undef $release
#undef $telse
#undef $throw
#undef $todo
#undef $uncomment
#undef $undefined_compiler
#undef $undefined_os
#undef $unlikely
#undef $warning
#undef $welse
#undef $windows
#undef $yes
#undef $$todo$stringize
#undef $$todo$stringize$impl
#undef $$warning$impl
